language: python

install:
  - pip install tox coveralls
matrix:
  include:
    - python: 2.7
      env:
          - ENV=docs
    - python: 2.7
      env:
          - ENV=py27-django18,py27-django19,py27-django110,py27-django111
    - python: 3.4
      env:
          - ENV=py34-django18,py34-django19,py34-django110,py34-django111,py34-django20
    - python: 3.5
      env:
          - ENV=py35-django18,py35-django19,py35-django110,py35-django111,py35-django20
    - python: 3.6
      env:
          - ENV=py36-django18,py36-django19,py36-django110,py36-django111,py36-django20
script:
  - tox -e $ENV
after_success:
  - coveralls
